### PR TITLE
Typo fix.

### PR DESCRIPTION
**Pull request by lilykriopelle**
Just cleaning up the README!

### CODE REVIEW

**Comment by bennostein** [comment]
LGTM!

**Comment by christiancho** [comment]
:shipit:

**Comment by josephecombs** [comment]
folks ITT need to lift more

**Comment by lilykriopelle** [comment]
@josephecombs is that really the best you can come up with? 

to be honest, I was hoping the bright mind that produced this genius app would be able to formulate a witty retort and/or engage in some quality discussion, but in retrospect, I guess that was a tad optimistic...I forgot you have to spend more time than most of us figuring out how to get women to sleep with you, so you don't have as much brain space left over for other things like intelligent conversation.

seriously though, I hope the quest to get laid is going well and you've come up with some better strategies that this one...failing that, I hope you've found some high-quality/low-cost hand lotion to keep yourself company.

**Comment by josephecombs** [comment]
You are truly demented person.  Seek psychological help.

**Comment by lilykriopelle** [comment]
@josephecombs the funny thing is, the more you talk, the more I see why an app like this might need to exist! maybe I misjudged it after all!

**Pull request closed without merging**
